elasticjob:
  regCenter:
    serverLists: 192.168.9.55:2181 #zk地址
    namespace: elasticjob-lite-springboot #命名空间
  jobs:
    myJob:
      elasticJobClass: test.job.MyJob #任务执行类
      cron: 0/5 * * * * ? #定时任务
      shardingTotalCount: 4 #分片总数
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou,3=QINGDAO #每个分片参数，格式：分片序号=分片参数
    secondJob:
      elasticJobClass: test.job.SecondJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
    missedTaskJob:
      elasticJobClass: test.job.MissedTaskJob
      cron: 0 1,3 10 * * ?
      shardingTotalCount: 1
      shardingItemParameters: 0=Beijing
      misfire: true #错过执行作业重触发
      failover: true #自动失效转移
    thirdJob:
      elasticJobClass: test.job.ThirdJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 2
      shardingItemParameters: 0=Beijing,1=Shanghai
    fourthJobIsScriptJob:
      elasticJobType: SCRIPT #任务类型为脚本
      cron: 0/10 * * * * ? #定时任务
      shardingTotalCount: 3 #分片总数
      props:
        script.command.line: "echo SCRIPT Job: " #脚本执行代码







